# Generated by Django 4.1.7 on 2023-04-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rewardPoints', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'passenger',
            },
        ),
    ]
